// Ordre Mafteiach (slugs) → noms FR / HE / alias de recherche / livre
window.PARSHIOT = [
 ['bereshit','Berechit','בראשית','bereishit bereshis genese',1],
 ['noach','Noa\'h','נח','noah noach noe',1],
 ['lech-lecha','Lekh Lekha','לך לך','lech lecha lekh lekha',1],
 ['vayeira','Vayéra','וירא','vayera vayeira',1],
 ['chayei-sarah','\'Hayé Sarah','חיי שרה','chayei sarah haye sara hayei',1],
 ['toledot','Toledot','תולדות','toldot toledot',1],
 ['vayetze','Vayétsé','ויצא','vayetze vayetzei vayeitzei vayetse',1],
 ['vayishlach','Vayichla\'h','וישלח','vayishlach vayishlah',1],
 ['vayeshev','Vayéchev','וישב','vayeshev vayechev',1],
 ['miketz','Mikets','מקץ','miketz mikeitz mikets',1],
 ['vayigash','Vayigach','ויגש','vayigash vayigach',1],
 ['vayechi','Vaye\'hi','ויחי','vayechi vayehi',1],
 ['shemot','Chemot','שמות','shemot shmot chemot exode',2],
 ['vaeira','Vaéra','וארא','vaera vaeira',2],
 ['bo','Bo','בא','bo',2],
 ['beshalach','Bechala\'h','בשלח','beshalach bechalah',2],
 ['yitro','Yitro','יתרו','yitro jethro',2],
 ['mishpatim','Michpatim','משפטים','mishpatim michpatim',2],
 ['terumah','Terouma','תרומה','terumah trumah terouma',2],
 ['tetzaveh','Tetsavé','תצוה','tetzaveh tetsave',2],
 ['ki-tisa','Ki Tissa','כי תשא','ki tisa tissa',2],
 ['vayakhel','Vayakhel','ויקהל','vayakhel',2],
 ['pekudei','Pekoudé','פקודי','pekudei pekoude',2],
 ['vayikra','Vayikra','ויקרא','vayikra levitique',3],
 ['tzav','Tsav','צו','tzav tsav',3],
 ['shemini','Chemini','שמיני','shemini chemini shmini',3],
 ['tazria','Tazria','תזריע','tazria',3],
 ['metzora','Metsora','מצורע','metzora metsora',3],
 ['acharei-mot','A\'haré Mot','אחרי','acharei achrei mot ahare',3],
 ['kedoshim','Kedochim','קדושים','kedoshim kedochim',3],
 ['emor','Emor','אמור','emor',3],
 ['behar','Behar','בהר','behar',3],
 ['bechukotai','Be\'houkotaï','בחוקותי','bechukotai behoukotai',3],
 ['bamidbar','Bamidbar','במדבר','bamidbar nombres',4],
 ['naso','Nasso','נשא','naso nasso',4],
 ['behaalotecha','Behaalotekha','בהעלותך','behaalotcha behaalotecha behaalotekha',4],
 ['shlach','Chela\'h','שלח','shlach shelach chelah',4],
 ['korach','Kora\'h','קרח','korach korah core',4],
 ['chukat','\'Houkat','חוקת','chukat houkat',4],
 ['balak','Balak','בלק','balak',4],
 ['pinchas','Pin\'has','פינחס','pinchas pinhas',4],
 ['matot','Matot','מטות','matot',4],
 ['masei','Massé','מסעי','masei masse',4],
 ['devarim','Devarim','דברים','devarim deuteronome',5],
 ['vaetchanan','Vaet\'hanan','ואתחנן','vaetchanan vaethanan',5],
 ['eikev','Ekev','עקב','eikev ekev',5],
 ['reah','Reé','ראה','reeh reah ree',5],
 ['shoftim','Choftim','שופטים','shoftim choftim',5],
 ['ki-teitzei','Ki Tétsé','כי תצא','ki teitzei tetse tetzei',5],
 ['ki-tavo','Ki Tavo','כי תבוא','ki tavo',5],
 ['nitzavim','Nitsavim','נצבים','nitzavim nitsavim',5],
 ['vayelech','Vayélekh','וילך','vayelech vayeilech vayelekh',5],
 ['haazinu','Haazinou','האזינו','haazinu haazinou',5],
 ['vzot-haberachah','Vezot Haberakha','וזאת הברכה','vezot haberachah vzot haberacha berakha',5],
];
window.BOOKS = {1:'Berechit',2:'Chemot',3:'Vayikra',4:'Bamidbar',5:'Devarim'};
